apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
name: ops
labels:
  nodetype: ops
spec:
  template:
    metadata:
      labels:
        nodetype: ops
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: ops
      requirements:
        - key: "nodetype"
          operator: In
          values:
            - ops
        - key: "kubernetes.io/arch"
          operator: In
          values:
            - amd64
        - key: "kubernetes.io/os"
          operator: In
          values:
            - linux
        - key: "karpenter.sh/capacity-type"
          operator: In
          values:
            - on-demand
        - key: "karpenter.sh/instance-family"
          operator: In
          values:
            - c7i
            - m7i
            - r7i
        - key: "karpenter.sh/instance-size"
          operator: In
          values:
            - large
            - xlarge
            - 2xlarge
            - 4xlarge
