apiVersion: v1
kind: Secret
metadata:
  name: eks-resources-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: eks-resources
  url: ssh://git@github.com/mlinfra-io/eks-resources
  project: "default"
  insecure: "true"
  enableLfs: "false"
