configuration: &configuration
  nodeSelector:
    nodetype: ops
  tolerations:
    - key: "nodetype"
      operator: "Equal"
      value: "ops"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nodetype
                operator: In
                values:
                  - ops

global:
  <<: *configuration
  logging:
    format: json
    level: info

redis:
  <<: *configuration

redis-ha:
  <<: *configuration
  enabled: true

redisSecretInit:
  <<: *configuration

controller:
  <<: *configuration
  replicas: 1

dex:
  <<: *configuration
  enabled: true

server:
  <<: *configuration
  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  <<: *configuration
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  <<: *configuration
  replicas: 2

notifications:
  <<: *configuration

commitServer:
  <<: *configuration
