configuration: &configuration
  nodeSelector:
    nodetype: ops
  tolerations:
    - key: "nodepool"
      operator: "Equal"
      value: "ops"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nodetype
                operator: In
                values:
                  - ops

global:
  <<: *configuration
  logging:
    format: json
    level: info

redis:
  <<: *configuration

redis-ha:
  <<: *configuration

redisSecretInit:
  <<: *configuration

controller:
  <<: *configuration

dex:
  <<: *configuration
  enabled: true

server:
  <<: *configuration

repoServer:
  <<: *configuration

applicationSet:
  <<: *configuration

notifications:
  <<: *configuration

commitServer:
  <<: *configuration
