spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    manifestsRepo: https://github.com/mlinfra-io/eks-resources
    targetRevision: HEAD
    path: hub/projects

applications:
  - name: karpenter
    repoURL: public.ecr.aws/karpenter
    chart: karpenter
    namespace: kube-system
    project: default
    createNamespace: false
    targetRevision: 1.8.5
    valueFiles:
      - values.yaml
  - name: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    chart: metrics-server
    namespace: metrics-server
    project: default
    createNamespace: true
    targetRevision: 3.13.0
    valueFiles:
      - values.yaml
  - name: vpc-cni
    repoURL: https://aws.github.io/eks-charts
    chart: aws-vpc-cni
    namespace: kube-system
    project: default
    createNamespace: false
    targetRevision: 1.21.0
    valueFiles:
      - values.yaml
