configuration: &configuration
  nodeSelector:
    nodetype: ops
  tolerations:
    - key: "nodetype"
      operator: "Equal"
      value: "ops"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nodetype
                operator: In
                values:
                  - ops

<<: *configuration

ambient:
  enabled: true

cni:
  cniBinDir: /opt/cni/bin
  cniConfDir: /etc/cni/net.d
  privileged: true
