configuration: &configuration
  nodeSelector:
    nodetype: ops
  tolerations:
    - key: "nodetype"
      operator: "Equal"
      value: "ops"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nodetype
                operator: In
                values:
                  - ops

<<: *configuration

clusterName: mlinfra-eks-cluster
defaultTargetType: ip
vpcId: vpc-0110b764bbcff91a4
